// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNith4-sml0XbUEHgLLwLCo4OMCgLiQ7Y',
    appId: '1:1090413429643:android:aba5b453d0bc7f18f0e58e',
    messagingSenderId: '1090413429643',
    projectId: 'points-counter-11f6d',
    databaseURL: 'https://points-counter-11f6d-default-rtdb.firebaseio.com',
    storageBucket: 'points-counter-11f6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CZ9bcK5ldowfpoCnklV7qQc-HrSqig4',
    appId: '1:1090413429643:ios:b91869ae55f167cff0e58e',
    messagingSenderId: '1090413429643',
    projectId: 'points-counter-11f6d',
    databaseURL: 'https://points-counter-11f6d-default-rtdb.firebaseio.com',
    storageBucket: 'points-counter-11f6d.firebasestorage.app',
    iosBundleId: 'com.spiderwebarts.pointsCounter',
  );

}